# Generated by Django 4.2.28 on 2026-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_jira_style_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
