# Generated by Django 4.2.30 on 2026-08-05 08:29

# Adds the custom field models: a property per work item type, its options and
# one row per (work item, property, value) with a typed column per property type
# so that filtering and ordering stay index friendly.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_seed_default_issue_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('TEXT', 'Text'), ('DECIMAL', 'Decimal'), ('OPTION', 'Option'), ('BOOLEAN', 'Boolean'), ('DATETIME', 'Datetime'), ('RELATION', 'Relation'), ('URL', 'URL'), ('EMAIL', 'Email'), ('FILE', 'File')], max_length=255)),
                ('relation_type', models.CharField(blank=True, choices=[('USER', 'User'), ('ISSUE', 'Issue')], max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_multi', models.BooleanField(default=False)),
                ('default_value', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('logo_props', models.JSONField(default=dict)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.issuetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_properties', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property',
                'verbose_name_plural': 'Issue Properties',
                'db_table': 'issue_properties',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('logo_props', models.JSONField(default=dict)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.issuepropertyoption')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_property_options', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Option',
                'verbose_name_plural': 'Issue Property Options',
                'db_table': 'issue_property_options',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('old_identifier', models.UUIDField(null=True)),
                ('new_identifier', models.UUIDField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('epoch', models.FloatField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_property_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_activities', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Activity',
                'verbose_name_plural': 'Issue Property Activities',
                'db_table': 'issue_property_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssuePropertyValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_decimal', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_uuid', models.UUIDField(blank=True, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.issueproperty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Property Value',
                'verbose_name_plural': 'Issue Property Values',
                'db_table': 'issue_property_values',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['issue', 'property'], name='ipv_issue_property_idx'), models.Index(fields=['property', 'value_uuid'], name='ipv_property_uuid_idx'), models.Index(fields=['property', 'value_decimal'], name='ipv_property_decimal_idx'), models.Index(fields=['property', 'value_datetime'], name='ipv_property_datetime_idx'), models.Index(fields=['property', 'value_boolean'], name='ipv_property_boolean_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='issuepropertyoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('property', 'name'), name='issue_property_option_unique_property_name_when_deleted_at_null'),
        ),
        migrations.AddIndex(
            model_name='issuepropertyactivity',
            index=models.Index(fields=['issue', 'property'], name='ipa_issue_property_idx'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_type', 'name'), name='issue_property_unique_issue_type_name_when_deleted_at_null'),
        ),
    ]
