# Generated by Django 4.2.30 on 2026-08-05 12:40

# A property value can now hang off a workspace draft instead of a work item, so
# the create modal can fill in custom fields on a draft. Converting the draft
# moves the values onto the work item it creates.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_issue_property_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuepropertyvalue",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_values",
                to="db.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuepropertyvalue",
            name="draft_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_values",
                to="db.draftissue",
            ),
        ),
        migrations.AddIndex(
            model_name="issuepropertyvalue",
            index=models.Index(fields=["draft_issue", "property"], name="ipv_draft_property_idx"),
        ),
    ]
