# Generated by Django 4.2.30 on 2026-08-05 12:48

# Filtering work items by a text property compares `value_text`, which nothing indexed.
# The index is a hash rather than a btree on purpose: a text value has no length bound
# and a btree entry over ~2704 bytes is refused outright, so a long value would fail to
# save. A hash index answers `=` only, which is the one text lookup an index can serve.

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_issue_property_value_draft_issue"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issuepropertyvalue",
            index=django.contrib.postgres.indexes.HashIndex(fields=["value_text"], name="ipv_value_text_hash_idx"),
        )
    ]
